(function () {
  const STORAGE_KEY = "attract-shun-home-language";

  const translations = {
    en: {
      headerEyebrow: "Intentional dating",
      navCreate: "Create Account",
      navSignIn: "Sign In",
      navDashboard: "Dashboard",
      navConnections: "Connections",
      navBrowse: "Browse",
      navMatch: "Match Flow",
      navSafety: "Safety",
      navStories: "Stories",
      navSettings: "Settings",
      navStudio: "Studio",
      heroEyebrow: "Intentional dating, rethought",
      badgeOneMatch: "One live match",
      badgeInterest: "Interest scores",
      badgeIntent: "Intentional dating",
      heroTitle: "One match at a time. Built for people who mean it.",
      heroCopy: "ATTRACT Shun is designed for intentional dating. One live match, guided milestones, and visible accountability keep attention on real connection instead of endless swiping.",
      ctaCreate: "Create Your Profile",
      ctaSignIn: "Sign In",
      systemLabel: "Focused dating system",
      pillarFocusLabel: "Focus",
      pillarFocusValue: "One active match at a time",
      pillarIntentLabel: "Intent",
      pillarIntentValue: "Built for intentional people only",
      pillarSignalLabel: "Signal",
      pillarSignalValue: "Every like carries a 1-10 interest score",
      pillarMomentumLabel: "Momentum",
      pillarMomentumValue: "Matches move from intro to date to decision",
      previewCopy: "Intentional, calm, ready for a relationship with real follow-through.",
      coreRuleKicker: "Core rule",
      coreRuleTitle: "Users can like many, but hold only one live match.",
      coreRuleCopy: "Incoming likes remain visible, but while a user is matched they cannot continue swiping or open new conversations.",
      intentKicker: "Intentional only",
      intentTitle: "Built for people who want a real relationship path.",
      intentCopy: "ATTRACT Shun is not for casual swiping. The product is shaped for people who want clear effort, real momentum, and intentional connection.",
      signalKicker: "Signal quality",
      signalTitle: "Every right swipe includes a 1 to 10 interest score.",
      signalCopy: "Mutual matches can immediately see how strongly the other person was interested before investing energy.",
      diagramOneKicker: "How the system works",
      diagramOneTitle: "A relationship path people can understand in seconds.",
      diagramOneCopy: "Instead of hiding the rules behind features, ATTRACT Shun makes the process visible: match, introduce, plan, decide. The structure itself becomes part of the product story.",
      diagramTwoKicker: "What a journey looks like",
      diagramTwoTitle: "Show one connection moving from interest to outcome.",
      diagramTwoCopy: "For a non-technical audience, a visual walkthrough lands faster than feature lists. This makes the product feel concrete and easy to imagine in use.",
      flowEyebrow: "Product flow",
      flowTitle: "The screens stay focused because the rules do the explaining",
      flowOneTitle: "Profile setup",
      flowOneCopy: "Create your profile, shape your standards, and define who should appear in discovery.",
      flowTwoTitle: "User dashboard",
      flowTwoCopy: "Track your account status, next action, interest signals, and current relationship state.",
      flowThreeTitle: "Browse and swipe",
      flowThreeCopy: "Review candidates in the same pool, pass, or swipe right with a required interest score.",
      flowFourTitle: "Active match",
      flowFourCopy: "Progress through intro video, date confirmation, chat, and attract-or-shun decision logic.",
      flowFiveTitle: "Trust and safety",
      flowFiveCopy: "Use visible policy enforcement and structured reporting to reduce games, ghosting, and bad behavior.",
      flowSixTitle: "Success and settings",
      flowSixCopy: "Capture testimonials after attract outcomes and manage visibility, notifications, and discovery preferences.",
      spotlightOneKicker: "Why it feels different",
      spotlightOneTitle: "Attention is earned here, not scattered.",
      spotlightOneCopy: "ATTRACT Shun removes the usual chaos of dating apps by forcing clarity. People know what they want, express how strongly they are interested, and move through a visible relationship path with deadlines.",
      spotlightTwoKicker: "Attract",
      spotlightTwoTitle: "Strong mutual interest becomes momentum.",
      spotlightTwoCopy: "When both people lean in, the app rewards clarity and makes next steps feel simple.",
      spotlightThreeKicker: "Shun",
      spotlightThreeTitle: "Bad behavior leaves a visible signal.",
      spotlightThreeCopy: "Ghosting, disrespect, and weak follow-through stop hiding behind infinite swiping.",
      languageShort: "Language",
      footerLeadEyebrow: "Built for clarity",
      footerLeadTitle: "A dating platform designed around focus, accountability, and real follow-through.",
      footerLeadCopy: "ATTRACT Shun is built for intentional people who want stronger signals, safer interactions, and a relationship path that does not hide behind endless swiping.",
      footerLegal: "Legal",
      footerPrivacy: "Privacy",
      footerConsumerPrivacy: "Consumer Health Data Privacy Policy",
      footerTerms: "Terms",
      footerCookies: "Cookie Policy",
      footerIP: "Intellectual Property",
      footerAccessibility: "Accessibility Statement",
      footerSupport: "Support",
      footerSafetyPolicy: "Safety Policy Information",
      footerFAQ: "FAQ",
      footerPress: "Press Room",
      footerContact: "Contact",
      footerGiftCards: "Gift Cards",
      footerPromo: "Promo Code",
      footerSocial: "Social",
      footerTechBlog: "Tech Blog",
      footerGetApp: "Get the app",
      footerIOS: "Download for iOS from the App Store",
      footerAndroid: "Download for Android from Google Play",
      footerCareers: "Careers",
      footerCareersPortal: "Careers Portal",
      footerDestinations: "Destinations",
      footerRights: "© 2026 ATTRACT Shun. All rights reserved.",
      appIosKicker: "Download for iOS",
      appIosLabel: "from the App Store",
      appAndroidKicker: "Download for Android",
      appAndroidLabel: "from Google Play",
    },
    es: {
      headerEyebrow: "Citas intencionales",
      navCreate: "Crear cuenta",
      navSignIn: "Iniciar sesión",
      navDashboard: "Panel",
      navConnections: "Conexiones",
      navBrowse: "Explorar",
      navMatch: "Flujo de match",
      navSafety: "Seguridad",
      navStories: "Historias",
      navSettings: "Ajustes",
      navStudio: "Studio",
      heroEyebrow: "Citas intencionales, replanteadas",
      badgeOneMatch: "Un match activo",
      badgeInterest: "Puntajes de interés",
      badgeIntent: "Citas intencionales",
      heroTitle: "Un match a la vez. Hecho para personas que van en serio.",
      heroCopy: "ATTRACT Shun está diseñado para citas intencionales. Un solo match activo, hitos guiados y responsabilidad visible mantienen la atención en la conexión real en lugar del deslizamiento infinito.",
      ctaCreate: "Crear tu perfil",
      ctaSignIn: "Iniciar sesión",
      systemLabel: "Sistema de citas enfocado",
      pillarFocusLabel: "Enfoque",
      pillarFocusValue: "Un match activo a la vez",
      pillarIntentLabel: "Intención",
      pillarIntentValue: "Hecho solo para personas intencionales",
      pillarSignalLabel: "Señal",
      pillarSignalValue: "Cada like lleva un puntaje de interés de 1 a 10",
      pillarMomentumLabel: "Impulso",
      pillarMomentumValue: "Los matches avanzan de presentación a cita y decisión",
      previewCopy: "Intencional, tranquila y lista para una relación con seguimiento real.",
      coreRuleKicker: "Regla central",
      coreRuleTitle: "Los usuarios pueden dar muchos likes, pero solo tener un match activo.",
      coreRuleCopy: "Los likes entrantes siguen visibles, pero mientras un usuario está en match no puede seguir deslizando ni abrir nuevas conversaciones.",
      intentKicker: "Solo intencional",
      intentTitle: "Hecho para personas que quieren un camino real de relación.",
      intentCopy: "ATTRACT Shun no es para citas casuales ni para deslizar sin rumbo. Está diseñado para personas que quieren esfuerzo claro, impulso real y conexión intencional.",
      signalKicker: "Calidad de señal",
      signalTitle: "Cada swipe a la derecha incluye un interés del 1 al 10.",
      signalCopy: "Los matches mutuos pueden ver de inmediato qué tan interesado estaba el otro antes de invertir energía.",
      diagramOneKicker: "Cómo funciona el sistema",
      diagramOneTitle: "Un camino de relación que la gente entiende en segundos.",
      diagramOneCopy: "En lugar de esconder las reglas detrás de funciones, ATTRACT Shun hace visible el proceso: match, presentación, plan y decisión. La estructura se vuelve parte de la historia del producto.",
      diagramTwoKicker: "Cómo se ve un recorrido",
      diagramTwoTitle: "Muestra una conexión desde el interés hasta el resultado.",
      diagramTwoCopy: "Para una audiencia no técnica, un recorrido visual funciona más rápido que una lista de funciones. Hace que el producto se sienta concreto y fácil de imaginar.",
      flowEyebrow: "Flujo del producto",
      flowTitle: "Las pantallas se mantienen enfocadas porque las reglas hacen la explicación",
      flowOneTitle: "Configuración del perfil",
      flowOneCopy: "Crea tu perfil, define tus estándares y establece quién debe aparecer en descubrimiento.",
      flowTwoTitle: "Panel del usuario",
      flowTwoCopy: "Sigue el estado de tu cuenta, la próxima acción, señales de interés y la relación actual.",
      flowThreeTitle: "Explorar y deslizar",
      flowThreeCopy: "Revisa candidatos del mismo grupo, pasa o desliza a la derecha con un puntaje requerido.",
      flowFourTitle: "Match activo",
      flowFourCopy: "Avanza por presentación en video, confirmación de cita, chat y decisión de attract o shun.",
      flowFiveTitle: "Confianza y seguridad",
      flowFiveCopy: "Usa políticas visibles y reportes estructurados para reducir juegos, ghosting y mal comportamiento.",
      flowSixTitle: "Éxitos y ajustes",
      flowSixCopy: "Guarda testimonios tras resultados attract y ajusta visibilidad, notificaciones y preferencias.",
      spotlightOneKicker: "Por qué se siente diferente",
      spotlightOneTitle: "La atención se gana aquí, no se dispersa.",
      spotlightOneCopy: "ATTRACT Shun elimina el caos habitual de las apps de citas al forzar claridad. La gente sabe lo que quiere, expresa cuánto interés tiene y avanza por un camino visible con tiempos definidos.",
      spotlightTwoKicker: "Attract",
      spotlightTwoTitle: "Un interés mutuo fuerte se convierte en impulso.",
      spotlightTwoCopy: "Cuando ambas personas se inclinan hacia adelante, la app recompensa la claridad y simplifica los próximos pasos.",
      spotlightThreeKicker: "Shun",
      spotlightThreeTitle: "El mal comportamiento deja una señal visible.",
      spotlightThreeCopy: "Ghosting, falta de respeto y mal seguimiento dejan de esconderse detrás del swipe infinito.",
      languageShort: "Idioma",
      footerLeadEyebrow: "Hecho para la claridad",
      footerLeadTitle: "Una plataforma de citas diseñada alrededor del enfoque, la responsabilidad y el seguimiento real.",
      footerLeadCopy: "ATTRACT Shun está hecho para personas intencionales que quieren señales más fuertes, interacciones más seguras y un camino de relación que no se esconda detrás del swipe infinito.",
      footerLegal: "Legal",
      footerPrivacy: "Privacidad",
      footerConsumerPrivacy: "Política de privacidad de datos de salud del consumidor",
      footerTerms: "Términos",
      footerCookies: "Política de cookies",
      footerIP: "Propiedad intelectual",
      footerAccessibility: "Declaración de accesibilidad",
      footerSupport: "Soporte",
      footerSafetyPolicy: "Información de políticas de seguridad",
      footerFAQ: "Preguntas frecuentes",
      footerPress: "Sala de prensa",
      footerContact: "Contacto",
      footerGiftCards: "Tarjetas de regalo",
      footerPromo: "Código promocional",
      footerSocial: "Social",
      footerTechBlog: "Blog técnico",
      footerGetApp: "Obtén la app",
      footerIOS: "Descargar para iOS desde App Store",
      footerAndroid: "Descargar para Android desde Google Play",
      footerCareers: "Empleos",
      footerCareersPortal: "Portal de carreras",
      footerDestinations: "Destinos",
      footerRights: "© 2026 ATTRACT Shun. Todos los derechos reservados.",
      appIosKicker: "Descargar para iOS",
      appIosLabel: "desde App Store",
      appAndroidKicker: "Descargar para Android",
      appAndroidLabel: "desde Google Play",
    },
    fr: {
      headerEyebrow: "Rencontres intentionnelles",
      navCreate: "Créer un compte",
      navSignIn: "Se connecter",
      navDashboard: "Tableau de bord",
      navConnections: "Connexions",
      navBrowse: "Découvrir",
      navMatch: "Parcours match",
      navSafety: "Sécurité",
      navStories: "Histoires",
      navSettings: "Réglages",
      navStudio: "Studio",
      heroEyebrow: "Les rencontres intentionnelles, repensées",
      badgeOneMatch: "Un match actif",
      badgeInterest: "Scores d’intérêt",
      badgeIntent: "Intention d’abord",
      heroTitle: "Un match à la fois. Conçu pour les gens sérieux.",
      heroCopy: "ATTRACT Shun est pensé pour des rencontres intentionnelles. Un seul match actif, des étapes guidées et une responsabilité visible gardent l’attention sur une vraie connexion plutôt que sur un swipe sans fin.",
      ctaCreate: "Créer votre profil",
      ctaSignIn: "Se connecter",
      systemLabel: "Système de rencontre ciblé",
      pillarFocusLabel: "Focus",
      pillarFocusValue: "Un seul match actif à la fois",
      pillarIntentLabel: "Intention",
      pillarIntentValue: "Pensé uniquement pour des personnes intentionnelles",
      pillarSignalLabel: "Signal",
      pillarSignalValue: "Chaque like porte un score d’intérêt de 1 à 10",
      pillarMomentumLabel: "Élan",
      pillarMomentumValue: "Les matches passent de l’intro au rendez-vous puis à la décision",
      previewCopy: "Intentionnelle, calme, prête pour une relation avec un vrai suivi.",
      coreRuleKicker: "Règle centrale",
      coreRuleTitle: "Les utilisateurs peuvent aimer plusieurs profils, mais n’avoir qu’un seul match actif.",
      coreRuleCopy: "Les likes reçus restent visibles, mais tant qu’un utilisateur est engagé dans un match il ne peut plus swiper ni ouvrir de nouvelles conversations.",
      intentKicker: "Intentions assumées",
      intentTitle: "Pensé pour ceux qui veulent un vrai parcours relationnel.",
      intentCopy: "ATTRACT Shun n’est pas conçu pour des rencontres casuales ou un swipe sans fin. Le produit s’adresse à des personnes qui veulent un effort clair, un vrai élan et une connexion intentionnelle.",
      signalKicker: "Qualité du signal",
      signalTitle: "Chaque swipe à droite inclut un score d’intérêt de 1 à 10.",
      signalCopy: "Les matches réciproques voient immédiatement à quel point l’autre était intéressé avant d’investir leur énergie.",
      diagramOneKicker: "Comment le système fonctionne",
      diagramOneTitle: "Un parcours relationnel que l’on comprend en quelques secondes.",
      diagramOneCopy: "Au lieu de cacher les règles derrière des fonctionnalités, ATTRACT Shun rend le processus visible : match, présentation, planification, décision. La structure elle-même devient une partie du produit.",
      diagramTwoKicker: "À quoi ressemble un parcours",
      diagramTwoTitle: "Montrer une connexion depuis l’intérêt jusqu’au résultat.",
      diagramTwoCopy: "Pour un public non technique, un parcours visuel fonctionne plus vite qu’une liste de fonctionnalités. Cela rend le produit concret et facile à imaginer.",
      flowEyebrow: "Parcours produit",
      flowTitle: "Les écrans restent concentrés parce que les règles font l’explication",
      flowOneTitle: "Configuration du profil",
      flowOneCopy: "Créez votre profil, définissez vos standards et choisissez qui doit apparaître dans la découverte.",
      flowTwoTitle: "Tableau de bord",
      flowTwoCopy: "Suivez l’état du compte, l’action suivante, les signaux d’intérêt et la situation relationnelle actuelle.",
      flowThreeTitle: "Découvrir et swiper",
      flowThreeCopy: "Parcourez les candidats du même pool, passez ou swipez à droite avec un score d’intérêt obligatoire.",
      flowFourTitle: "Match actif",
      flowFourCopy: "Progressez à travers l’intro vidéo, la confirmation du rendez-vous, le chat et la logique attract ou shun.",
      flowFiveTitle: "Confiance et sécurité",
      flowFiveCopy: "Utilisez une politique visible et des signalements structurés pour réduire les jeux, le ghosting et les mauvais comportements.",
      flowSixTitle: "Succès et réglages",
      flowSixCopy: "Recueillez des témoignages après un attract et gérez la visibilité, les notifications et les préférences.",
      spotlightOneKicker: "Pourquoi c’est différent",
      spotlightOneTitle: "Ici, l’attention se mérite, elle ne se disperse pas.",
      spotlightOneCopy: "ATTRACT Shun enlève le chaos habituel des apps de rencontre en imposant la clarté. Les gens savent ce qu’ils veulent, expriment leur niveau d’intérêt et avancent dans un parcours relationnel visible avec des délais.",
      spotlightTwoKicker: "Attract",
      spotlightTwoTitle: "Un fort intérêt mutuel devient un élan.",
      spotlightTwoCopy: "Quand les deux personnes s’impliquent, l’application récompense la clarté et simplifie la suite.",
      spotlightThreeKicker: "Shun",
      spotlightThreeTitle: "Les mauvais comportements laissent un signal visible.",
      spotlightThreeCopy: "Le ghosting, l’impolitesse et le manque de suivi ne peuvent plus se cacher derrière le swipe infini.",
      languageShort: "Langue",
      footerLeadEyebrow: "Pensé pour la clarté",
      footerLeadTitle: "Une plateforme de rencontre conçue autour du focus, de la responsabilité et d’un vrai suivi.",
      footerLeadCopy: "ATTRACT Shun est conçu pour des personnes intentionnelles qui veulent des signaux plus forts, des interactions plus sûres et un parcours relationnel qui ne se cache pas derrière un swipe infini.",
      footerLegal: "Légal",
      footerPrivacy: "Confidentialité",
      footerConsumerPrivacy: "Politique de confidentialité des données santé consommateurs",
      footerTerms: "Conditions",
      footerCookies: "Politique de cookies",
      footerIP: "Propriété intellectuelle",
      footerAccessibility: "Déclaration d’accessibilité",
      footerSupport: "Support",
      footerSafetyPolicy: "Informations sur la politique de sécurité",
      footerFAQ: "FAQ",
      footerPress: "Espace presse",
      footerContact: "Contact",
      footerGiftCards: "Cartes cadeaux",
      footerPromo: "Code promo",
      footerSocial: "Social",
      footerTechBlog: "Blog tech",
      footerGetApp: "Télécharger l’app",
      footerIOS: "Télécharger pour iOS depuis l’App Store",
      footerAndroid: "Télécharger pour Android depuis Google Play",
      footerCareers: "Carrières",
      footerCareersPortal: "Portail carrières",
      footerDestinations: "Destinations",
      footerRights: "© 2026 ATTRACT Shun. Tous droits réservés.",
      appIosKicker: "Télécharger pour iOS",
      appIosLabel: "depuis l’App Store",
      appAndroidKicker: "Télécharger pour Android",
      appAndroidLabel: "depuis Google Play",
    },
    pt: {
      headerEyebrow: "Relacionamento intencional",
      navCreate: "Criar conta",
      navSignIn: "Entrar",
      navDashboard: "Painel",
      navConnections: "Conexões",
      navBrowse: "Explorar",
      navMatch: "Fluxo de match",
      navSafety: "Segurança",
      navStories: "Histórias",
      navSettings: "Configurações",
      navStudio: "Studio",
      heroEyebrow: "Relacionamento intencional, repensado",
      badgeOneMatch: "Um match ativo",
      badgeInterest: "Pontuações de interesse",
      badgeIntent: "Namoro intencional",
      heroTitle: "Um match de cada vez. Feito para quem leva isso a sério.",
      heroCopy: "ATTRACT Shun foi criado para um namoro intencional. Um único match ativo, etapas guiadas e responsabilidade visível mantêm a atenção na conexão real em vez do swipe infinito.",
      ctaCreate: "Criar seu perfil",
      ctaSignIn: "Entrar",
      systemLabel: "Sistema de namoro focado",
      pillarFocusLabel: "Foco",
      pillarFocusValue: "Um match ativo por vez",
      pillarIntentLabel: "Intenção",
      pillarIntentValue: "Feito apenas para pessoas intencionais",
      pillarSignalLabel: "Sinal",
      pillarSignalValue: "Cada curtida carrega uma nota de interesse de 1 a 10",
      pillarMomentumLabel: "Momento",
      pillarMomentumValue: "Os matches avançam de apresentação para encontro e decisão",
      previewCopy: "Intencional, calma e pronta para um relacionamento com constância real.",
      coreRuleKicker: "Regra principal",
      coreRuleTitle: "Os usuários podem curtir muitos perfis, mas ter apenas um match ativo.",
      coreRuleCopy: "As curtidas recebidas continuam visíveis, mas enquanto a pessoa está em um match ela não pode continuar deslizando nem abrir novas conversas.",
      intentKicker: "Somente intencional",
      intentTitle: "Feito para pessoas que querem um caminho real de relacionamento.",
      intentCopy: "ATTRACT Shun não é para encontros casuais nem swipe sem direção. O produto foi desenhado para pessoas que querem esforço claro, impulso real e conexão intencional.",
      signalKicker: "Qualidade do sinal",
      signalTitle: "Cada swipe para a direita inclui uma nota de interesse de 1 a 10.",
      signalCopy: "Matches mútuos conseguem ver imediatamente o nível de interesse da outra pessoa antes de investir energia.",
      diagramOneKicker: "Como o sistema funciona",
      diagramOneTitle: "Um caminho de relacionamento que as pessoas entendem em segundos.",
      diagramOneCopy: "Em vez de esconder as regras atrás de recursos, ATTRACT Shun torna o processo visível: match, apresentação, plano e decisão. A própria estrutura vira parte da história do produto.",
      diagramTwoKicker: "Como a jornada parece",
      diagramTwoTitle: "Mostre uma conexão indo do interesse ao resultado.",
      diagramTwoCopy: "Para um público não técnico, um passo a passo visual funciona melhor do que listas de recursos. Isso torna o produto concreto e fácil de imaginar em uso.",
      flowEyebrow: "Fluxo do produto",
      flowTitle: "As telas permanecem focadas porque as regras fazem a explicação",
      flowOneTitle: "Configuração do perfil",
      flowOneCopy: "Crie seu perfil, defina seus padrões e molde quem deve aparecer na descoberta.",
      flowTwoTitle: "Painel do usuário",
      flowTwoCopy: "Acompanhe o status da conta, a próxima ação, sinais de interesse e o estado atual do relacionamento.",
      flowThreeTitle: "Explorar e deslizar",
      flowThreeCopy: "Veja candidatos do mesmo grupo, passe ou deslize para a direita com uma nota obrigatória.",
      flowFourTitle: "Match ativo",
      flowFourCopy: "Avance por vídeo de apresentação, confirmação de encontro, chat e decisão de attract ou shun.",
      flowFiveTitle: "Confiança e segurança",
      flowFiveCopy: "Use política visível e denúncias estruturadas para reduzir jogos, ghosting e mau comportamento.",
      flowSixTitle: "Sucesso e configurações",
      flowSixCopy: "Registre depoimentos após resultados attract e controle visibilidade, notificações e preferências.",
      spotlightOneKicker: "Por que parece diferente",
      spotlightOneTitle: "A atenção é conquistada aqui, não dispersa.",
      spotlightOneCopy: "ATTRACT Shun remove o caos comum dos apps de namoro ao forçar clareza. As pessoas sabem o que querem, mostram o quanto estão interessadas e avançam por um caminho visível com prazos.",
      spotlightTwoKicker: "Attract",
      spotlightTwoTitle: "Interesse mútuo forte vira impulso.",
      spotlightTwoCopy: "Quando os dois se envolvem, o app recompensa a clareza e torna o próximo passo simples.",
      spotlightThreeKicker: "Shun",
      spotlightThreeTitle: "Mau comportamento deixa um sinal visível.",
      spotlightThreeCopy: "Ghosting, desrespeito e falta de constância deixam de se esconder atrás do swipe infinito.",
      languageShort: "Idioma",
      footerLeadEyebrow: "Feito para clareza",
      footerLeadTitle: "Uma plataforma de namoro desenhada em torno de foco, responsabilidade e continuidade real.",
      footerLeadCopy: "ATTRACT Shun foi criado para pessoas intencionais que querem sinais mais fortes, interações mais seguras e um caminho de relacionamento que não se esconda atrás do swipe infinito.",
      footerLegal: "Jurídico",
      footerPrivacy: "Privacidade",
      footerConsumerPrivacy: "Política de privacidade de dados de saúde do consumidor",
      footerTerms: "Termos",
      footerCookies: "Política de cookies",
      footerIP: "Propriedade intelectual",
      footerAccessibility: "Declaração de acessibilidade",
      footerSupport: "Suporte",
      footerSafetyPolicy: "Informações de política de segurança",
      footerFAQ: "FAQ",
      footerPress: "Sala de imprensa",
      footerContact: "Contato",
      footerGiftCards: "Cartões-presente",
      footerPromo: "Código promocional",
      footerSocial: "Social",
      footerTechBlog: "Blog técnico",
      footerGetApp: "Baixe o app",
      footerIOS: "Baixar para iOS na App Store",
      footerAndroid: "Baixar para Android no Google Play",
      footerCareers: "Carreiras",
      footerCareersPortal: "Portal de carreiras",
      footerDestinations: "Destinos",
      footerRights: "© 2026 ATTRACT Shun. Todos os direitos reservados.",
      appIosKicker: "Baixar para iOS",
      appIosLabel: "na App Store",
      appAndroidKicker: "Baixar para Android",
      appAndroidLabel: "no Google Play",
    },
  };

  const languageNames = {
    en: "English",
    es: "Español",
    fr: "Français",
    pt: "Português",
  };

  function applyLanguage(language) {
    const copy = translations[language] || translations.en;
    document.documentElement.lang = language;
    document.querySelectorAll("[data-i18n]").forEach((node) => {
      const key = node.dataset.i18n;
      if (copy[key]) node.textContent = copy[key];
    });
    const currentLabel = document.getElementById("language-current");
    if (currentLabel) currentLabel.textContent = `(${languageNames[language] || languageNames.en})`;
    localStorage.setItem(STORAGE_KEY, language);
  }

  const saved = localStorage.getItem(STORAGE_KEY) || "en";
  applyLanguage(translations[saved] ? saved : "en");

  const languageTrigger = document.getElementById("language-trigger");
  const languageSheet = document.getElementById("language-sheet");
  const languageSheetClose = document.getElementById("language-sheet-close");
  const languageSheetBackdrop = document.getElementById("language-sheet-backdrop");

  function openLanguageSheet() {
    if (!languageSheet) return;
    languageSheet.hidden = false;
    document.body.classList.add("language-sheet-open");
  }

  function closeLanguageSheet() {
    if (!languageSheet) return;
    languageSheet.hidden = true;
    document.body.classList.remove("language-sheet-open");
  }

  languageTrigger?.addEventListener("click", () => {
    openLanguageSheet();
  });

  languageSheetClose?.addEventListener("click", closeLanguageSheet);
  languageSheetBackdrop?.addEventListener("click", closeLanguageSheet);
  languageSheet?.querySelectorAll(".language-option-button").forEach((button) => {
    button.addEventListener("click", () => {
      applyLanguage(button.dataset.language);
      closeLanguageSheet();
    });
  });

  const iosAppButton = document.getElementById("ios-app-button");
  iosAppButton?.addEventListener("click", () => {
    window.AppUI.showModal({
      title: "Coming soon",
      body: "The ATTRACT Shun iPhone app is in progress and will be announced soon.",
      primaryLabel: "Close",
      secondaryLabel: "",
      onPrimary: () => {},
    });
  });

  const androidAppButton = document.getElementById("android-app-button");
  androidAppButton?.addEventListener("click", () => {
    window.AppUI.showModal({
      title: "Coming soon",
      body: "The ATTRACT Shun Android app is in progress and will be announced soon.",
      primaryLabel: "Close",
      secondaryLabel: "",
      onPrimary: () => {},
    });
  });
})();
